#!/usr/bin/env python

accelerate launch textual_inversion.py \
  --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --use_auth_token \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=3000 \
  --learning_rate=5.0e-04 --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --train_data_dir="dragon" \
  --learnable_property="style" \
  --placeholder_token="<spyro-dragon>" \
  --initializer_token="game" \
  --output_dir="textual_inversion_spyro-dragon"